baseURL = "https://tappeddev.github.io/tapped-website/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme-adjusted"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false


[languages]
  [languages.en]
    weight = 2
  [languages.de]
    weight = 1

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "menuAbout"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "menuService"
  URL = "#service"
  weight = 3

  [[menu.header]]
  name = "menuClients"
  URL = "#clients"
  weight = 4

  [[menu.header]]
  name = "menuWorks"
  URL = "#works"
  weight = 5

  [[menu.header]]
  name = "menuTechnologies"
  URL = "#technologies"
  weight = 6

  [[menu.header]]
  name = "menuTestimonials"
  URL = "#testimonials"
  weight = 7

  [[menu.header]]
  name = "menuContact"
  URL = "#contact"
  weight = 8

  [[menu.header]]
  name = "menuJobs"
  URL = "jobs/"
  weight = 9

  [[menu.footer]]
  name = "menuLegalNotice"
  URL = "legal_notice"
  weight = 2

  [[menu.footer]]
  name = "menuGeneralConditions"
  URL = "general_conditions"
  weight = 3

  [[menu.footer]]
  name = "menuPrivacy"
  URL = "privacy"
  weight = 4


[params]

  googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Andreas"
    text2 = "Ellure"

  [params.footer]
      copyright = "© Tapped UG (Haftungsbeschränkt). All rights reserved."
